site_name: tziakcha_record_miner
theme:
  name: material

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Analyzer: analyzer/analyzer_cli.md
  - Base: 
      - Record: base/record.md
      - Constants: base/tziakcha_constants.md
  - Calc: calc/calc_cli.md
  - Fetcher: fetcher/fetcher_cli.md
