site_name: tziakcha_record_miner
site_url: https://miner.choimoe.com
theme:
  name: material

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 首页: index.md
  - 牌谱分析: analyzer/analyzer_cli.md
  - 通用:
      - 雀渣牌谱记录: base/record.md
      - 雀渣常量: base/tziakcha_constants.md
      - CHAGA API: base/chaga.md
  - 计算工具: calc/calc_cli.md
  - 爬虫工具: fetcher/fetcher_cli.md
