site_name: tziakcha_record_miner
theme:
  name: material

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Analyzer: analyzer/
  - Base: base/
  - Calc: calc/
  - Fetcher: fetcher/
